#### 1. numpy import 방법 & 버젼 체크

In [1]:
import numpy as np

np.__version__

'1.20.1'

#### 2. 3 x 4 1D array 만들기

In [27]:
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 3.  3 x 3 boolean array 만들기

In [16]:
np.full((3,3), True, dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
np.full(9,True).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
np.full((3,3), bool(1))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.ones(9 , dtype=bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 4. array에서 홀수만 뽑아내기

In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0]  # boolean indexing

array([1, 3, 5, 7, 9])

In [30]:
arr[1::2] #  슬라이싱

array([1, 3, 5, 7, 9])

#### 5. 주어진 조건에 만족하는 원소를 다른 값으로 대체하기

In [38]:
# 짝수만 -1 로 바꿔보자 

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==0] = -1
arr

# 이러면 0까지 -1로 바뀌게 된다
# 엄밀히 말해 0은 짝수가 아니다

array([2, 4, 6, 8])

In [52]:
# 따라서 조건을 다르게 바꿔줘야 한다.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr%2==0) & (arr!=0)] = -1
arr

array([ 0,  1, -1,  3, -1,  5, -1,  7, -1,  9])

#### 6. 기존 array 에 영향을 주지 않고 주어진 조건을 만족하는 원소를 다른 값으로 대체하기

In [58]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr%2==1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 7. reshape 하기

In [60]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 8. 두 array를 수직으로 쌓기

In [67]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(7, 10).reshape(2,5)

In [68]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
b

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [74]:
# 방법1
np.concatenate((a,b), axis=0)    # a,b  부분은 array-like

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [78]:
# 방법2
np.vstack([a,b])   # a,b  부분은 array-like

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [83]:
# 방법3
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

#### 9. 두 array를 수평으로 붙이기

In [85]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(7, 10).reshape(2,5)

In [87]:
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]))

In [95]:
# 방법1
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 7, 7, 7, 7, 7],
       [5, 6, 7, 8, 9, 7, 7, 7, 7, 7]])

In [97]:
# 방법2
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 7, 7, 7, 7, 7],
       [5, 6, 7, 8, 9, 7, 7, 7, 7, 7]])

In [93]:
# 방법3
np.c_[a,b]

array([[0, 1, 2, 3, 4, 7, 7, 7, 7, 7],
       [5, 6, 7, 8, 9, 7, 7, 7, 7, 7]])

In [ ]:
# a,b  부분은 array-like

#### 10. numpy함수만 사용하여 예시와 같은 array 생성하기

In [99]:
# 예시) array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])

In [108]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [103]:
np.concatenate([a,a,a], axis=0)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [107]:
np.hstack([np.repeat(a,3), np.concatenate([a,a,a], axis=0)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [110]:
np.r_[np.repeat(a,3), np.concatenate([a,a,a], axis=0)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])