#### 1. pandas import 방법 & 버젼 체크

In [1]:
import numpy as np # 넘파이도 당연히 필요함
import pandas as pd

pd.__version__  # 버젼 체크

'1.2.4'

#### 2. list, numpy array, dict 로 Series 생성하기

In [8]:
mylist = list('abcedfghijklmnopqrstuvwxyz')  #list
myarr = np.arange(26)  # array
mydict = dict(zip(mylist, myarr))  # dict

pd.Series(mylist)
pd.Series(myarr)
pd.Series(mydict).head() # 5상위 5개만 출력하는 함수 head()

a    0
b    1
c    2
e    3
d    4
dtype: int64

#### 3. Series 의 index를 DataFrame  의 column으로 변환하기

In [14]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
ser.head()  # 인덱스가 a,b,c....

a    0
b    1
c    2
e    3
d    4
dtype: int64

In [16]:
ser.index  # 인덱스가 a,b,c....

Index(['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='object')

In [24]:
ser.to_frame().reset_index().head()  # 기존의 인덱스를 컬럼으로 올리는 함수 reset_index()

index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4

#### 4. 다수의 Series를 결합하여 DataFrame 으로 만들기

In [27]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

ser1.head(3), ser2.head(3)

(0    a
 1    b
 2    c
 dtype: object,
 0    0
 1    1
 2    2
 dtype: int32)

In [29]:
# ser1 + ser2  # 이렇게 된다면 너무 좋겠지만...? 

In [40]:
# 방법 1
pd.concat([ser1, ser2], axis=1).head()  # pandas 의 pd.concat() 함수

0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

In [43]:
# 방법 2
pd.DataFrame(data={'col1' : ser1, 'col2' : ser2}).head()

# data= 는 생략가능, data가 dict일 경우 column의 순서는 삽입된 순서를 따른다.

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [59]:
pd.DataFrame(ser1, index=[i+1 for i in range(26)], columns = ['col1']).head()

col1
1    b
2    c
3    e
4    d
5    f

#### 5. Series의 index에 이름을 지정하기

In [60]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [65]:
ser.name = '알파벳'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: 알파벳, dtype: object

#### 6. Series B에 없는 Series A의 내용을 가져오기

In [67]:
ser1 = pd.Series([1, 2, 3, 4, 5])  # Series A
ser2 = pd.Series([4, 5, 6, 7, 8])  # Series B
ser1, ser2

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int64,
 0    4
 1    5
 2    6
 3    7
 4    8
 dtype: int64)

In [76]:
ser1[ser1.isin(ser2)]   # 인덱싱을 isin() 함수로

# 이러면 ser1에 있는 내용중  ser2에도 있는 내용을 가져오게 된다.

3    4
4    5
dtype: int64

In [77]:
# 따라서 부정을 의미하는 ~ 연산자를 앞에 붙여준다
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

#### 7. 각각의 시리즈에 중복된값은 빼고 합치기

In [80]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [98]:
np.union1d(ser1, ser2)

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [99]:
np.intersect1d(ser1, ser2)

array([4, 5], dtype=int64)

In [109]:
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
pd.DataFrame(ser_u[~ser_u.isin(ser_i)], columns=['열'])

열
0  1
1  2
2  3
5  6
6  7
7  8

#### 8. numeric Series 의 최소값, 최대값, 평균, 중간값, 25%, 75% 구하기

In [115]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [121]:
ser.head()

0     9.786615
1    15.971146
2    22.431677
3     7.114372
4     9.839652
dtype: float64

In [118]:
# 최소값
ser.min(), np.min(ser)

(-2.4791368272044316, -2.4791368272044316)

In [119]:
# 최대값
ser.max(), np.max(ser)

(22.431676906490026, 22.431676906490026)

In [122]:
# 평균
ser.mean(), np.mean(ser)

(9.426186104619838, 9.426186104619838)

In [123]:
# 중간값
ser.median(), np.median(ser)

(10.75959577538253, 10.75959577538253)

In [131]:
# 25%
np.percentile(ser, 25)

6.279183536929125

In [132]:
# 75%
np.percentile(ser, 75)

12.18236231657599

In [135]:
# 한꺼번에도 가능
np.percentile(ser, (0,25,50,75,100))  # 0과 100은 각각 최대값, 최소값이 된다

array([-2.47913683,  6.27918354, 10.75959578, 12.18236232, 22.43167691])

#### 9. Series 내용의 빈도수 구하기

In [141]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=300)))

In [148]:
ser

0      c
1      a
2      e
3      b
4      e
      ..
295    b
296    f
297    b
298    c
299    c
Length: 300, dtype: object

In [149]:
ser.unique()  # 각각의 유니크한 값

array(['c', 'a', 'e', 'b', 'g', 'h', 'd', 'f'], dtype=object)

In [150]:
ser.value_counts()

d    43
c    42
h    40
f    38
e    37
b    36
a    35
g    29
dtype: int64

- 9-1. 빈도가 40 이상인 행만  나타내기

In [162]:
result = ser.value_counts()
result_df = pd.DataFrame(result[result>=40])
result_df

0
d  43
c  42
h  40

#### 10. 가장 빈도가 높은 상위 2개의 값만 유지하고 나머지 값은 'other' 로 바꾸기

In [215]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 10, [200]))
ser

0      7
1      3
2      6
3      2
4      4
      ..
195    5
196    8
197    9
198    7
199    4
Length: 200, dtype: int32

In [216]:
result = ser.value_counts()  # sort= True 가장 빈도수 높은거부터 내림차순 정렬이 디폴트
result

7    28
5    26
4    24
6    22
2    21
3    21
1    20
8    19
9    19
dtype: int64

In [217]:
result.index[:2]  # 7 과 5가 상위 2개 값이다. 따라서

Int64Index([7, 5], dtype='int64')

In [214]:
# boolean 인덱싱으로 상위 두개 값을 포함 하지 "않은" 원소들은 모두 'other' 로 교체한다.
ser[~ser.isin(result.index[:2])] = 'other'
ser

0      other
1      other
2          9
3      other
4      other
       ...  
195    other
196    other
197        9
198    other
199        9
Length: 200, dtype: object

In [221]:
pd.DataFrame(ser.value_counts()[:2])  

0
7  28
5  26